services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"        
    ports:
      - "1433:1433"
    volumes:
      - sql-db-data:/var/opt/mssql/data
volumes: 
  sql-db-data:
